# Generated by Django 3.1.8 on 2022-06-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=200)),
                ('s_mobile_no', models.IntegerField()),
                ('view_type', models.CharField(max_length=100)),
            ],
        ),
    ]
