# Generated by Django 3.1.8 on 2022-06-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenericViews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostumerData',
            new_name='CustomerData',
        ),
    ]
